### PR TITLE
Add Caliburn.Micro as a framework option

### LINKED ISSUE #438: Add Caliburn.Micro as a framework option
I would like to add in the [Caliburn.Micro](http://caliburnmicro.com/) framework.  It is a very popular framework and would work great in the project.

@nigel-sampson is the framework creator and will be on point for integrating.

### PR DESCRIPTION
**Pull request by nigel-sampson**
This PR adds Caliburn.Micro as a framework option and supports all features and page templates (Resolves #438).

- The automated tests should be green.
- Docs still need to be updated.
- There should be no breaking changes.
- Requires #1139 for correct behavior of most features templates.

### CODE REVIEW

**Comment by nigel-sampson** [comment]
Looks like the unit tests have updated since yesterday, will create out the appropriate ones.

**Comment by sibille** [comment]
We changed the tests yesterday to be separated by framework to be able to run them concurrently. 
Let me have a look your tests and see if I can integrate them in the new testing strategy.

**Comment by nigel-sampson** [comment]
Just making the changes now, should have the commits in the next half hour then happy for you to review :smile:

**Comment by nigel-sampson** [comment]
Thanks, will look into the PR and check the .md file.

**Comment by sibille** [comment]
Great!!
Another two issues we detected in our templates, that affect yours two: 
#1082 and #1112.
I'll prepare a PR with the applied fixes

**Comment by mrlacey** [comment]
Were the "odd characters" an encoding issue, or some other scenario we could have tested for?

**Comment by nigel-sampson** [comment]
Looks like it slipped in on [this commit](https://github.com/Microsoft/WindowsTemplateStudio/commit/9444e2264afee7ea0d5843aa48b3dd169d60e0ba#diff-d3702da2ab7e0b88fc049353face5bae) which I'm fairly sure was triggered by a test failing, suspect a mistake on my part.

**Comment by ralarcon** [comment]
Looks like there is a StyleCop violation with the `Services\ThemeSelectorService.cd`: error SA1508: A closing brace must not be preceded by a blank line.

**Comment by nigel-sampson** [comment]
Will fix this up tonight, thanks for the merge.

**Comment by nigel-sampson** [comment]
Thanks @sibille, beat me by ten minutes :smile:

**Pull request merged**
