### PR TITLE
Fix status cleaning

### PR DESCRIPTION
**Pull request by mvegaca**
Check if current Status in wizar can be cleaned before clean it.

Quick summary of changes
- Which issue does this PR relate to?
#757

### CODE REVIEW

**Comment by crutkas** [comment]
the naming is unclear, totally not sure what this does

**Comment by mvegaca** [comment]
The problem was that in the wizard there are processes that can update or clean the top status bar, in this case, templates update process was cleaning the status when it finishes with no pending updates. I've added a property in status that specifies if this status could be cleaned (information status are cleanable and warning and error status not). Can you approve the PR to can confirm the solution on dev nightly?

**Comment by mrlacey** [comment]
Is this code using the word "clean" instead of "clear"?

**Comment by mvegaca** [comment]
CleanStatus is when the status is setted as empty, for example, "looking for templates..." -> " "

**Comment by mrlacey** [comment]
Yes, but that's not what "clean" means

**Comment by crutkas** [comment]
I'm trying to wrap my head around this, this feels awkward from an implementation standpoint.  It is unclear how the fix here actually corrects #757 as 757 feels like a race condition where something is causing it to close early due to an older timer or condition or something being triggered.

As a dev, if i called `StatusViewModel.Error("foo", true, 15);` versus `StatusViewModel.Error("foo", false, 15);`.  Or `StatusViewModel.Error("foo", false, 0);` and then called `StatusViewModel.Error("bar", false, 0);` i don't know what exactly would happen.

When i think about a dialog as well, it is either Transient or Persistent dialog

- A transient message disappears based on time (or something else)
- A persistent message would stay up until a direct action corrects it (error fixed, user closed, ...)

When would either of these states not be cleared out when it goes away or another warning super-succeeds it.  I think the type of dialog also would be thought about for our we handle our markdown modals for.  (that is a different topic however).

Naming wise as well, i agree with Matt, you're clearing, not cleaning.  Cleaning would be something like destroying references and closing streams.

**Comment by mvegaca** [comment]
Naming updates added. For another release, I would like to think about a different and unified message display method, that allows having a status pool to read all notifications, with some improvements. If there are one status showing and one thread wants to show a new status, this new status keep in a pool until the current message is autohide or closed, defining different priorities.
Can @crutkas approve the PR and merge the code?

**Comment by crutkas** [comment]
@mvegaca, there is a conflict, can't merge

**Pull request merged**
