### PR TITLE
I1976 command line

### PR DESCRIPTION
**Pull request by mrlacey**
For #1976

Add a new feature for enabling launching the app from the command line and handling any arguments passed to it.

Note. Because of the way UWP handles the activation of apps from the command line, I've had to include a work-around to keep data ready for when Prism wants it in it's activation flow.

This was previously blocked by a dependency on having RS4 as the minimum target platform in the generated app.

This is currently a draft as it will require modifications to associated docs once #3303 is merged.

### CODE REVIEW

**Comment by mrlacey** [comment]
@sibille it's not clear what the AzureDevOp build failure is caused by can you investigate?
- and is there a bot command to trigger the PR build agent to try again?

(If #3304 is merged first this may require some manual merge fixes)

**Comment by sibille** [comment]
Will look into it, appveyor is failing due to a trailing whitespace.

**Comment by sibille** [comment]
@mrlacey, changed the test run configuration and re-ran, you should be able to see the complete test log now on https://winappstudio.visualstudio.com/DefaultCollection/WTS/_build/results?buildId=31212, can you confirm?

**Comment by mrlacey** [comment]
> @mrlacey, changed the test run configuration and re-ran, you should be able to see the complete test log now on https://winappstudio.visualstudio.com/DefaultCollection/WTS/_build/results?buildId=31212, can you confirm?

Yes, I can see the details.
Merge complete and repushed.

**Pull request merged**
