### PR TITLE
Check container recreation in OnBackgroundActivated

### LINKED ISSUE #2632: [Prism] Background activation should not recreate container
### Repro steps

Repro steps on clean project:
- Add at least 2 pages
- Add background task
- Trigger background task through VS
- Navigate

### Expected Behavior

Navigation is succesful.

### Actual Behavior

While testing #2621 (on a private repo) I received following exception on first navigation after the event got fired.

> Microsoft.Practices.Unity.ResolutionFailedException: 'Resolution of the dependency failed, type = "XXX.ViewModels.YYYViewModel", name = "(none)".
> Exception occurred while: while resolving.
> Exception is: InvalidOperationException - The current type, Prism.Windows.Navigation.INavigationService, is an interface and cannot be constructed. Are you missing a type mapping?

## System

* **VS Version:** 15.8.5
* **WTS Wizard Version:** 2.4.18260.1
* **WTS Template Version:** 2.4.18260.1
* **Windows Build:**

### PR DESCRIPTION
**Pull request by bartlannoeye**
## PR checklist

Quick summary of changes

- Which issue does this PR relate to? Fixes #2632 
- Anything that requires particular review or attention? Check explanation in issue to see if I forgot something.
- Do all automated tests pass? No reference found in tests, didn't rerun whole suite.
- Have automated tests been added for new features? No
- Have you raised issues for any needed follow-on work? No
- Have docs been updated? No reference found
- If breaking changes or different ways of doing things have been introduced, have they been communicated widely? **This probably should be added to the changelog for existing apps with Prism and background tasks.**

### CODE REVIEW

**Comment by crutkas** [comment]
this should be on the main readme i think.

**Comment by bartlannoeye** [comment]
Since the background task is in-process, it's terminated as well and can't re-activate a terminated app. Am I correct?

I've tested following cases (manually through VS lifecycle states):

* background task (on running app)
* suspend - resume
* suspend - background task - resume
* suspend and shutdown - launch

All worked fine.

**Comment by bartlannoeye** [comment]
Looks like there's one more step to be tested (see issue). I'll look at it tonight, can stay open for now.

**Comment by bartlannoeye** [comment]
Quick update: making progress on this, but checking a few more items to see for the best solution. Out of town for 2 days, so picking this up again over the weekend.

**Comment by sibille** [comment]
@bartlannoeye, what's the status for this pr?

**Comment by bartlannoeye** [comment]
Hey @sibille, the complexity of trying to make it work with the current release, combined with multiple events (attending and/or speaking) resulted in taking a bit longer. I've done a "best-effort" fix which handles 95% of all use cases and described the last edge case (which should rarely happen) in the linked issue. We'll have to take this last one in our next Prism release.

It's an improvement over the current code in WTS, so if the team agrees, I would suggest to merge this PR and we'll do our best to get the next release out the door asap.

**Comment by sibille** [comment]
Thanks @bartlannoeye, sounds good to me!

**Pull request merged**
