### PR TITLE
Sync core хочу написать бота телеграм

### PR DESCRIPTION
**Pull request by googleQ7**
## PR checklist

Quick summary of changes

- Which issue does this PR relate to?
- Anything that requires particular review or attention?
- Do all automated tests pass?
- Have automated tests been added for new features?
- If you've changed the UI: 
  - Be sure you are including screenshots to show the changes.
  - Be sure you have reviewed the [accessibility checklist](accessibility.md).
- If you've included a new template: 
  - Be sure you reviewed the [Template Verification Checklist](https://github.com/Microsoft/WindowsTemplateStudio/wiki/Template-Verification-Checklist).
- Have you raised issues for any needed follow-on work?
- Have docs been updated?
- If breaking changes or different ways of doing things have been introduced, have they been communicated widely?

### CODE REVIEW

**Comment by crutkas** [comment]
What is this pull request for?

**Comment by googleQ7** [comment]
я только учусь. хочу сделать чат бота телеграм



>Воскресенье, 21 апреля 2019, 8:15 +03:00 от Clint Rutkas <notifications@github.com>:
>
>What is this pull request for?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
м к

**Comment by mrlacey** [comment]
Google Translate says:

"Sync core I want to write a bot telegram"
"I am just learning. I want to make chat bot telegram"

**Comment by googleQ7** [comment]
I just recently became interested in development. I don't understand much yet. but i like it


>Воскресенье, 21 апреля 2019, 11:21 +03:00 от Matt Lacey <notifications@github.com>:
>
>Google Translate says:
>"Sync core I want to write a bot telegram"
>"I am just learning. I want to make chat bot telegram"
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
м к

**Comment by crutkas** [comment]
@googleq7 sorry, but what is the Pull Request for / about. There isn’t a linking issue to understand the scope of the change / why the changes were done

**Comment by crutkas** [comment]
Actually based on commits, these are David’s commits it seems like

**Comment by sibille** [comment]
@crutkas, yes, those are davids commits to sync core with wints. We're doing this in a separate branch until version 3.2 is released. @googleQ7, could you fork the repo and do the tests there?

**Comment by googleQ7** [comment]
подскажите где это сделать

**Pull request closed without merging**
