### PR TITLE
New feature: URI Scheme (protocol) support

### PR DESCRIPTION
**Pull request by mrlacey**
#506

### CODE REVIEW

**Comment by crutkas** [comment]
i looked at this, looks good, i want to run it before i approve

**Comment by crutkas** [comment]
@mrlacey ran it, looks good.  i thought the idea of a hidden page was interesting.  would a message prompt make this feature a lot lighter versus an entire new page?  or is it you want to demonstrate the e.Parameter usage?

I'm also going to have app model team give it a quick once over as well.

**Comment by mrlacey** [comment]
@crutkas My expectation is that a major use case is using a protocol launch to navigate to specific pages within an app. (It's core to Rome Web-to-app and in many Cortana skill examples.) Beyond the home page, there's no page guaranteed to be in the created app and so it requires the inclusion of an extra page to show this functionality. 
Using an extra/hidden page was always my [plan](https://github.com/Microsoft/WindowsTemplateStudio/issues/506#issuecomment-310859649), for the purpose of demonstrating how to pass parameters from the Uri Query and for completeness. In that there will be people who want to do this it's easier to have the people who don't ignore or remove it than to add more documentation to try and explain how.

**Comment by crutkas** [comment]
Got the review, approach looks good.  Per before, i think navigating to an extra page adds a bit of load on us but I understand the reasoning.

**Pull request merged**
