### PR TITLE
Delete solution directory to cancel button click, only if directory is empy.

### PR DESCRIPTION
**Pull request by dgomezc**
## PR checklist

Quick summary of changes

- Which issue does this PR relate to?
#882  #967

### CODE REVIEW

**Comment by crutkas** [comment]
how does this fix the storage.ide issue?  Should we increase any unit tests here?

**Comment by crutkas** [comment]
Also should we move this logic out of UI and into core?

**Comment by ralarcon** [comment]
What do you mean with storage.ide issue? Agree to check if we can add some unit tests. Apart from that, it is not strightfoward to move this to other place as we only can catch the "escape / cancel" action thru handling the _WizardBackoutException_ which occurs at UI level. 

We already have some methods which delete folders but this concrete combination do not looks to much reusable (IMHO)...

**Comment by crutkas** [comment]
storage.ide was mentioned in https://github.com/Microsoft/WindowsTemplateStudio/issues/967

**Pull request merged**
