### PR TITLE
Issue1037 template validator

### PR DESCRIPTION
**Pull request by mrlacey**
For #1037 ## PR checklist

- Adds a new tool to validate template files.
- Also, runs the tools tests as part of the automated tests.
- Included some changes to the templates for issues found during the creation of the tool.
- Includes appropriate addition to the template docs.

The original intention behind creating this tool was to help me when creating templates but I also hope it will be useful to others. If not found to be used/useful it can be re-evaluated at a later time. If wider use is adopted I'd like to add some unit tests to ensure it continues to function as intended. I don't feel spending time on such tests at the moment would not be the best use of my time.

Also, introduces a new external dependency but that also uses the MIT license and isn't included in anything that is installed.

### CODE REVIEW

**Comment by ralarcon** [comment]
@mrlacey, can you please add the "Analyze" configuration for the `TemplateValidator.csproj`, it is just a copy but in this configuration the "analisys" is enabled at build time by default and causes build to fail if there is a rule violation. This is the configuration we use in the CI to ensure the StyleCop rules being verified.

**Comment by mrlacey** [comment]
@ralarcon It' looks like it's the "Any CPU" vs "AnyCPU" issue where the Solution version doesn't match the project version but I can't see how this is different from other projects in the solution. Can you see what's wrong?

**Comment by ralarcon** [comment]
Yes, let me have a look on it...

**Comment by ralarcon** [comment]
@mrlacey... your change was right and the Big.sln builds perfectly... the thing is that the solution used to run the CI in AppVeyor is "AppVeyorCI.sln", so is in this solution where we need to add the project and the new configuration (Analyze) for the TemplatesValidator project. 

I needed to create the AppVeyorCI.sln solution since the AppVeyor build server was not able to build the Installer.2017 project (it does not have installed the Visual Studio Extension capabilities). What I do not understand is why the TemplateValidator project is being build because it is not in the solution itself (maybe because it was doing a nuget restore for the big.sln)

**Comment by mrlacey** [comment]
Yep, added to the AppVeyorCI.sln and all works. 
My guess is that it found the project and tried to build it because `Templates.Test` has a reference to it so it can run automatically all the tests against the templates we ship.

**Pull request merged**
