### PR TITLE
Fixed issue #417: copyrightYear parameter (must be under symbols)

### PR DESCRIPTION
**Pull request by sibille**
Fixed issue #417: copyrightYear parameter (must be under symbols)

### CODE REVIEW

**Comment by crutkas** [comment]
Why is this getting merged into master?

**Comment by ralarcon** [comment]
This is a hotfix to correct #417 just in case we want to release a new version of templates. 

It is already fixed in dev but the project templates definition has been changed (merged from three projects to just one) and it will not needed to be merged back to dev.

**Comment by crutkas** [comment]
I don't think we need to do a hot fix for this.

**Comment by ralarcon** [comment]
Removing this PR as we will not deploying a hotfix for this.

**Pull request closed without merging**
