### PR TITLE
Automatic culture setting

### PR DESCRIPTION
**Pull request by Luk164**
Quick summary of changes

- Related to issue #3667
- I could not get the entire repo to work so I did not run automated tests.
- Did not update documentation
- The only real change is that the entire app will apply culture setting based on the operating system

This is my first time trying to create a pull request so if I did anything wrong please do correct me.

### CODE REVIEW

**Comment by mrlacey** [comment]
This only addresses WPF code. Is the problem you're trying to address specific to WPF?

**Comment by Luk164** [comment]
> This only addresses WPF code. Is the problem you're trying to address specific to WPF?

Yes it is

**Comment by sibille** [comment]
@Luk164 , you said you had problems in getting the entire repo to work. Did you go through the docs at https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-developers.md? That should give you all the info to get started. If there's anything missing or not working as expected, please raise an issue to get it fixed.

**Comment by sibille** [comment]
@Luk164, closing this in favor of https://github.com/microsoft/WindowsTemplateStudio/pull/3767. More info on #3667.

**Pull request closed without merging**
