### PR TITLE
Extend minimum test execution set

### PR DESCRIPTION
**Pull request by ralarcon**
Included the Generation+Build of all project combinations (Frameworks and Project Types) with all features and pages in the Minimum execution set. This will increase the generation+build tests surface to catch more issues within the CI

- Which issue does this PR relate to?
#1104

- Anything that requires particular review or attention?
The build time for CI will be increased to run the minimum execution set (expected 10-15 mins now).

- Do all automated tests pass?
Yes

### CODE REVIEW

**Comment by ralarcon** [comment]
Not sure why it fails in the AppVeyor instance... locally the tests are working... tomorrow will investigate further.

**Comment by mrlacey** [comment]
VB tests don't yet need to be run as part of the minimum set

**Comment by mrlacey** [comment]
> VB tests don't yet need to be run as part of the minimum set.

From **Microsoft.Templates.Core.ProgrammingLanguages** in the dev branch
```
public static IEnumerable<string> GetAllLanguages()
{
    yield return ProgrammingLanguages.CSharp;
    yield return ProgrammingLanguages.VisualBasic;  // This is currently disabled until full VB support is enabled
}
```

The above was created as part of the preparation work for VB. The second yield line was commented out when the VB work was merged and the comment line made sense (it's not disabled when uncommented) as there was nothing that should be being done with the VB templates for v1.3.

Because this line has been uncommented the automated tests are doing, potentially, twice as much work as they _currently_ need to.

This is now the second thing related to VB functionality that has been added to the executing code when it shouldn't have.
EIther someone is enabling this as part of something else and not explaining or understanding the consequences. 
Or lots of changes are being incorporated into PRs that shouldn't be.
With so many tests not working as they should or disabled, this leaves me very concerned about the state of the code in general, and even more on the approach to a release.

**Comment by ralarcon** [comment]
@mrlacey, it was me as part of the other change... I've included this to run the VB projects as I enabled the VB in the installer... I thought it was needed :D

**Pull request merged**
