### PR TITLE
Added documentation on which tests are run in which build

### PR DESCRIPTION
**Pull request by sibille**
Quick summary of changes
Added documentation on which tests are run in which build
- Which issue does this PR relate to?
#831

### CODE REVIEW

**Comment by mrlacey** [comment]
This is a good start but it also needs to be clearer about which build relates to which column on the home page. Is "Templates.Test.Gen" the same as "Templates Publishing"?

image

Is it even true that a build passing includes all related tests passing?

Related: it would also be good if the results on the readme page indicated when they were last run and against which branch.

**Comment by sibille** [comment]
Good point, I'll adjust the names in the documentation to what we use in the Build Status table. 
Yes, failing tests will make build fail.

**Comment by ralarcon** [comment]
@mrlacey, you shoud check the dev branch page (not merged to master yet).

**Comment by mrlacey** [comment]
@ralarcon not everyone who looks at the project will know to look to the dev branch to see the latest.
This also highlights that changes to this doc should be applied to master more frequently too.

**Pull request merged**
