### PR TITLE
Update for UWP Toolkit 2.0, UWP .NET 5.3.3

### PR DESCRIPTION
**Pull request by crutkas**
## PR checklist

Quick summary of changes

- Which issue does this PR relate to?
#1045
- Anything that requires particular review or attention?
5.3.3 UWP had to be updated due to UWP Toolkit 2.0
- Do all automated tests pass?
yup

### CODE REVIEW

**Comment by ralarcon** [comment]
I made a small test an using the Visual Studio 15.3 references by default 5.4. so, maybe we could think in update the csproj / vbproj to reference this (but this would impact people running other Visual Studio Viersions)
``` xml
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>5.4.0</Version>
    </PackageReference>
```
I would like to verify if the Visual Studio 15.3 includes the 5.3.3 / 5.4 and the behavior on vanilla machines (without having compiled any app) to verifiy that the project creation time (generation + nuger.restore) does not have impact when run from Visual Studio 15.3 (when it runs from 15.0 it will, as the Universal Platform distributed is 5.3.2.

**Comment by ralarcon** [comment]
Closed by error... :D

**Comment by ralarcon** [comment]
Verified. Pointing to UniversalWindowsPlatform 5.3.3 causes a big delay restoring the packages because of the download of packages from nuget. I will check with 5.4 as it looks to be the default in Visual Studio 15.3 (so I guess it is delivered as part of it).

**Comment by ralarcon** [comment]
Using 5.4, and creating a BLANK app (Universal) takes a while to be created (it put 2,5GB in the nuget chache). If the we open a WTS, it takes a while too to be opened too (and it adds about 1 GB more to the nuget cache)... I bet that creating a WTS app with the nuget cache empty will take about the same time using 5.3.3. than using 5.4. So we need to decide what we prefer... or maybe we can delay this for 1.4 and align it with the VS2017 15.4 (which I know will have more changes and improvements).

**Comment by crutkas** [comment]
agreed.  @mrlacey, i don't know if i see a strong reason currently for us to upgrade to 2.0 until 15.4 rtms.

i'm fine with the 5.4 update but by the time 15.4 rolls around, I'm pretty sure the default package will be 6.0.0

**Comment by ralarcon** [comment]
Build failure is from a test.

Project Templates currently configured to TargetVersion 10.0.15063.0 and NETCore.UniversalWindowsPlatform 5.4.0. When ready, those values will be upgraded to 10.0.16XXX.0 and 6.0.0

**Pull request merged**
