### PR TITLE
Fix styling of Nav Menu items

### PR DESCRIPTION
**Pull request by mrlacey**
Changes based on January redlines
#364

### CODE REVIEW

**Comment by skendrot** [comment]
I don't agree with the selected rectangle height. The News app, Weather, Feedback Hub, Groove all have the height of the selection to be the full height of the row. Seems like Settings is the only one that is unique

**Comment by ralarcon** [comment]
@mrlacey I gues #412 would be related with this.

**Comment by mrlacey** [comment]
please don't delete this branch yet. more to come.....

**Comment by mrlacey** [comment]
@ralarcon yes, #412 is also fixed by #408

**Pull request merged**
