### PR TITLE
Issue772 doc

### PR DESCRIPTION
**Pull request by mvegaca**
Issue #772
Added LiveTile doc and samples.
The samples include:
- Activation for LiveTile icon update.
- Activation for SecondaryTile icon.
- Different pages for SecondarySection and LiveTileUpdatePage.

The samples are implemented on CodeBehind, MVVMBasic and MVVMLight framworks.

### CODE REVIEW

**Comment by mvegaca** [comment]
Could you please add a grammar review @mrlacey ??

**Comment by ralarcon** [comment]
@mrlacey could you please add your review?

**Comment by mrlacey** [comment]
I can't approve this.

1. It doesn't address the original issue.
2. It contains lots that seems redundant.
3. There is text in the documentation where I can't correct the grammar as I can't work out what it's trying to say.
4. It doesn't include a complete set of samples.

In reverse order.

We now have four officially supported frameworks. If we're providing framework specific examples this should include all the frameworks. It's not appropriate to require Nigel to write the CM version of everything. As we add support for more frameworks this will require learning those frameworks and/or collaborating on changes with people who are more familiar with those frameworks before submitting a PR to /dev.
Samples are also something we should avoid unless there's no other alternative. They're awkward and costly to maintain plus they are hard to point to from the generated code. We now have the situation where the generated code says "you need to do something, go look at this doc" (or it should--but I can't see it in the PR) then the doc says "now go look at this sample". This re-direction seems unnecessary and subject to more maintenance overhead over time.

The structure of the documentation can be summed up as
- The files that are added to the project
- Some of the code from the added files
- The code you must add to your project
- A link to samples of the above

This raises a number of questions in my mind
- Why include the copy of the code from the generated project? If it's not clear then it should be improved or comment in the code added.
- If the code that needs to be added is in the document, why is the sample needed?
- If the code must be added in every app why can't it be included in the generated code?.....


And now the fundamental issue.
I raised #722 as it feels like the feature only contains part of what's necessary for that feature.
The generated project that includes that feature isn't complete and doesn't work fully.

The Live Tile feature should (IMHO) include three things
1. Code to pin or update a tile
2. An example of how to call the code added in 1
3. Handling activation of the app from a tile.

We currently only do 1 & 2. The original issue is that we should include 3 as well.

Every app that uses the feature will _have_ to implement the activation code. Not including a base version of the activation handling code but requiring everyone to have to go and look at the docs and copy from there does not feel like the best solution we can provide.
As with most of the other code we generate, we should be providing something that works but with TODO comments in the code to show where changes have to be made.

When I did the UriScheme feature I deliberately included the activation handling because
- it meant there was less for the developer to do
- it wasn't necessary to require them to go and look elsewhere to know what needed to change
- it was easier to test what was included in the generated test.

The last point was particularly important for me as I needed to manually verify that the generated code worked correctly. If I hadn't included that code I've needed to manually add it for each variation of output (projectType/framework) to do the testing. (Did anyone manually add that code to test the feature when it was originally added? I'm skeptical and concerned that if we don't do this it will make adding automated testing of the generated feature harder.)

There are other features that also suffer from a lack of including the logic to handle activation. I think we'd benefit from reviewing/discussing/improving these all together. There _may_ be a benefit for some reuse in the templates needed to add all the missing activation handlers but this may be missed if they're reviewed separately.

@crutkas @ralarcon we might want to turn this into a bigger discussion / separate issue. Keen to talk more about this.

**Comment by ralarcon** [comment]
I think the PR try to cover what whas defined in the #772, probably not in the best way, but at the end of the thread @mvegaca clearly expressed that he was going to add some documentation to help understand the usage. No one expresed against that, so we went ahead.

@crutkas, @mrlacey close this PR if you think does not have value. If not, please, let me know which part of the content are understandable and we try to reauthor.

I agree with the fact of adding the pages / features with sample code if required is more maintainable than create samples, but this goes directly against the original concept of avoid to create non-final code and avoid the developers to remove generated code. We can do it, we just need to define it as the default. In the other hand, our audience is the developers, I think the samples are perfectly understandable without having to include variations for all frameworks and project types.

**Comment by mrlacey** [comment]
This whole discussion raises the need to be clearer about what the goals of the project are and how to achieve them.

There's lots of contradiction going on here and it's not productive.

> "avoid to create non-final code and avoid the developers to remove generated code"

This contradicts the fact that we already include "sample" code for LiveTile, Toast Notifications, and anything using SampleData. We do it because what would be generated otherwise would be half complete.
There are also lots of places where we add code with a TODO comment saying it needs changing or implementing. This is "non-final" but is both necessary and beneficial.

My argument is that this is half complete as it doesn't include details of how to handle the activation.
I acknowledge that we can't implement everything as it will be needed in the final app but that doesn't mean we should do nothing.
All I was asking for in the original issue was some code in the `HandleActivationAsync` method in `LiveTileService` (and `ToastNotificationService`) so that launching the app wouldn't leave it in a state where no page was navigated to. In this scenario, the app is in a state which it should never be and can easily be considered a bug. As another of the goals of the project is to output a working app. While it's not a final app it should work without behavior that looks like a bug.

Being clear about the aims and what we can and should include would also benefit #358 which has turned into the gathering of ideas for example code to generate. That is code that is intended only to serve as an example of how to use a specific API. That is code that should also be deleted and so is non-final.


> In the other hand, our audience is the developers, I think the samples are perfectly understandable

It's always dangerous to make assumptions about the people who will use a piece of software as they will vary widely in terms of knowledge and experience. We know this is especially true as WTS is targeted at those just getting started as well as experienced developers. We also know from issues like #886 that people want help with things that we might consider basic.
Not all the developers who use the tool will think about or understand code the same way as you.
If we're going to have samples then not covering the different ways that the code should behave with different frameworks will mean that some people will be unlikely to follow the sample. But, I still feel it's better to not need samples at all.

I also don't agree that not objecting to a subjective statement about one way to address an issue is the same as approving that it should be done that way.  I don't have the time or desire to review and respond to every comment on every issue. I already spend more time reviewing changes and responding to issues than I do working on improvements directly and that's not how I want to spend the time I'm volunteering.

**Comment by ralarcon** [comment]
@mrlacey I hear you. I'm the first one interested in delivering quality and value to our developers.

Probably I didn't select the most appropiated wording. Instead of "avoid", I should have used "reduce". That is, to reduce as far as possible the use of non-final code. This is what is in our minds, but of course, the measurment of what is the amount of acceptable sample code depends on the eyes, background and experience of who is looking at the code.

Thinking in positive, I don't have any interest in supporting documentation as it is more difficult and costly than having working code. The code for the sample was there just to support the doc. 

My assumptions arround developers were in the sense that even having different framworks, my understanding is that it is not absolutely mandatory to have al the variations for a sample as the samples inplace were not too complex. This happen even in docs.microsoft.com, not all [samples](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.sharetarget.shareoperation) are always in all languages. 

Finally, don't get me wrong, we appreciate and value your criticism as it make us to be better. I wasn't saying that the way to afford the issue was approved and accepted by all... As you mention the issue (and that the PR didn't address it), I was just mentioning that the PR was in line with what was discussed in the issue, even if it wasn't the best / ideal approach, nothing else. 

This is not dramatic for us to close this PR, if we think we can achieve the target using other way.

**Pull request closed without merging**
