### PR TITLE
Translated templates\Features and templates\Pages

### PR DESCRIPTION
**Pull request by Nukepayload2**
## PR checklist

Quick summary of changes

Translated C# templates in \templates\Features and \templates\Pages into VB.
Not tested yet.

- Which issue does this PR relate to?
#863, #371 
- Anything that requires particular review or attention?
The translation is still incomplete.
- Do all automated tests pass?
No. Because I haven't translated \templates\_composition and other parts yet.
- Have automated tests been added for new features?
No.
- If you've changed the UI: 
  - Be sure you are including screenshots to show the changes
  - Be sure you have reviewed the [accesibility checklist](accessibility.md)
I haven't changed the UI.
- Have you raised issues for any needed follow-on work?
#371 
- Have docs been updated?
No.
- If breaking changes or different ways of doing things have been introduced, have they been communicated widely.
No breaking change(s).

### CODE REVIEW

**Comment by mrlacey** [comment]
Even if we ignore the merge conflicts there are other things that would make merging these changes impossible.
- Without the composition templates that accompany the above pages and features the generated code wouldn't work. Plus some projects would fail to generate.
- The templates in this PR are not configured correctly. The wizard wouldn't load anything and it would actually break all the C# templates as well.
- As this breaks pretty much all functionality it would need to all be fixed to get anything working. Trying to fix such a large number of issues is challenging and very slow. The reason that other commits to this branch only add a page or feature at a time is to ensure that everything continues to work while the new templates are added. This is much easier when the amount that changes is small.
- The code in this PR causes many of our automated tests to fail. These tests not only check that the functionality works but there is a level of standardization and consistency in all that's generated. Failure to meet this standard makes future maintenance harder and doesn't meet the high-quality bar we want for the generated projects.

While the effort you've made it appreciated, it's not going to be feasible to accept this pull request.

**Comment by ralarcon** [comment]
By the way, this PR is huge.  It will be very difficult to make reviews to all those changes at once. I can suggest here some coordination to handle what is being incorporated and what are the goals, plans, etc.

**Comment by mrlacey** [comment]
@Nukepayload2 I don't want you wasting your time here. There is no point submitting versions of templates that already exist in that branch unless you have identified bugs in whats there and are fixing them. If you do this, please make a small, focused fixes that address the specific issue.
If you want to port some of the feature templates that haven't yet been done, let me know and I'll leave them to you. Any PR needs to include code that will pass all test and be complete. The reality of reviewing 921 merged files at once is tiny. It definitely won't happen if the code doesn't pass the automated tests.

**Comment by Nukepayload2** [comment]
I'll try to make a good pull request next time.

**Pull request closed without merging**
