### PR TITLE
Fix Suspend and Resume Service

### PR DESCRIPTION
**Pull request by dgomezc**
## PR checklist

Quick summary of changes

- Which issue does this PR relate to?
#2794 - Exception closing app using unmodified SuspendAndResumeService - Unable to remove the file to be replaced

### CODE REVIEW

**Comment by crutkas** [comment]
@michael-hawker are you ok with this fix as is.  We are still investigating per the email thread for maybe a deeper fix

**Comment by michael-hawker** [comment]
@crutkas yup, I think I added a loop in mine to try again to save, but this is a good starting point.  The only suggestion I have (assuming you don't mind changing the interface) is to have it return a `Task<bool>` so upstream could also handle the response.  

But don't know how you generally handle interface changes, so this is sufficient for a first step until we find the right folks in the platform to talk to about these calls.

**Comment by crutkas** [comment]
@dgomezc can you do the change @michael-hawker  recommended?

**Comment by dgomezc** [comment]
@crutkas @michael-hawker just added the changes.

**Pull request merged**
