### PR TITLE
Split new project pages and features on two different steps and some …

### PR DESCRIPTION
**Pull request by mvegaca**
Issue #607 Split new project pages and features on two different steps and some ViewModels refactor

### CODE REVIEW

**Comment by crutkas** [comment]
@mvegaca looks to be a conflict

**Comment by mvegaca** [comment]
Thanks, @crutkas, please do not merge this PR, I need to add more things tomorrow.

**Comment by sibille** [comment]
@mrlacey, new UI.Test project is about adding unit tests for viewmodel logic

**Comment by ralarcon** [comment]
@mrlacely I will dismiss your review as the UI.Test is needed now.

**Pull request merged**
