### PR TITLE
Added UriScheme feature.

### PR DESCRIPTION
**Pull request by Nukepayload2**
## PR checklist

Quick summary of changes
Ported UriScheme feature for Visual Basic.

- Which issue does this PR relate to?
#863 
- Anything that requires particular review or attention?
Unit tests of WACK are failed due to hard coded project file extension (".csproj") in unit test code.
- Do all automated tests pass?
Except WACK tests.
- Have automated tests been added for new features?
No.
- If you've changed the UI: 
  - Be sure you are including screenshots to show the changes
  - Be sure you have reviewed the [accesibility checklist](accessibility.md)
- Have you raised issues for any needed follow-on work?
- Have docs been updated?
- If breaking changes or different ways of doing things have been introduced, have they been communicated widely.

### CODE REVIEW

**Comment by ralarcon** [comment]
@mrlacey as this PR is against vb templates branch, I wait for you to review it and merge.

**Comment by mrlacey** [comment]
For reference `GetPagesAndFeaturesForMultiLanguageProjectsAndFrameworks` in `Microsoft.Templates.Test.BaseGenAndBuildTests` contains a list of pages and features that are fully supported in both languages. This is used by the test `EnsureProjectsGeneratedWithDifferentLanguagesAreEquivalentAsync`.
It's also how we're tracking what can be demoed as part fo work-in-progress.

**Comment by crutkas** [comment]
here is a Q, are we running the VB code through the exact same unit functionality tests as the c#?

**Comment by mrlacey** [comment]
> are we running the VB code through the exact same unit functionality tests as the c#?

and more!
There are additional tests that compare the output of projects generated with the same options but different languages.
There will also be more tests added before this goes live.

**Pull request merged**
