### PR TITLE
Update Param_ProjectName.Tests.xUnit.csproj - Add reference to Microsoft.NET.Test.Sdk

### PR DESCRIPTION
**Pull request by scottkuhl**
Add reference to Microsoft.NET.Test.Sdk.

# PR checklist

**Quick summary of changes**

**Which issue does this PR relate to?** 3940

**Applies to the following platforms:**

| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| Yes | ? |? |

**Anything that requires particular review or attention?**

**Do all automated tests pass?**

**Have automated tests been added for new features?** No

**If you've changed the UI:** No
  - Be sure you are including screenshots to show the changes.
  - Be sure you have reviewed the [accessibility checklist](accessibility.md).

**If you've included a new template:** No
  - Be sure you reviewed the [Template Verification Checklist](https://github.com/microsoft/WindowsTemplateStudio/wiki/Checklist:-Template-Verification).
  - Be sure it's included in the list on this [UWP](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/getting-started-endusers.md) or [WPF](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/WPF/getting-started-endusers.md) getting started doc.

**Have you raised issues for any needed follow-on work?** No

**Have docs been updated?** n/a

**If breaking changes or different ways of doing things have been introduced, have they been communicated widely?** n/a

### CODE REVIEW

**Comment by scottkuhl** [comment]
This is my first PR on this project.  I'm not sure if I updated the template correctly.

**Comment by mrlacey** [comment]
NuGet package dependencies need to be specified in template.json files. This is to ensure that the NuGet Package Restore process is run correctly. If the reference is added to the project file directly it is necessary to manually run the NuGet restore process before the code can be compiled. This can be confusing for people generating apps for the first time. It also makes automated testing harder.

For this issue the file to change is https://github.com/microsoft/WindowsTemplateStudio/blob/dev/templates/Uwp/Testing/UnitTests.App.xUnit/.template.config/template.json

The fix should be to update the version of xunit.runner.visualstudio AND add a reference to the latest version of Microsoft.NET.Test.Sdk (16.8.0)

This also impacts the VB version and so a similar change is needed in https://github.com/microsoft/WindowsTemplateStudio/blob/dev/templates/Uwp/Testing/UnitTests.App.xUnit._VB/.template.config/template.json

**Comment by scottkuhl** [comment]
I updated the version across all the test projects.  Most of them had the references they needed they just needed version bumps.

**Comment by sibille** [comment]
Thanks @scottkuhl for your contribution! 
Updates on Microsoft.NET.Test.Sdk and WinAppDriver look good to me.
I don't think we can update xunit.visualstudio.runner as the build pipeline reports "error APPX0702: Payload file 'C:\Packs\xunit.runner.visualstudio\2.4.3\build\uap10.0.16299\xunit.runner.reporters.netstandard11.dll' does not exist."
Same happens for me locally, did this work for you when adding the reference directly on the project?

**Comment by scottkuhl** [comment]
That error is hit and miss.  I was able to get it work by first updating the Test SDK and then updating the xunit runner.

**Comment by scottkuhl** [comment]
Would you like me to downgrade xunit runner to 2.4.1?  It seems more stable.

**Comment by sibille** [comment]
Yes, I think we should stay on xunit runner 2.4.1

**Comment by scottkuhl** [comment]
Downgrade is done.

**Comment by sibille** [comment]
Thanks @scottkuhl!

**Review by sibille — APPROVED** [review]

**Comment by sibille** [comment]
PR build pipeline suceeded, but did not report back: https://winappstudio.visualstudio.com/WTS/_build/results?buildId=35517&view=results

**Pull request merged**
