### PR TITLE
Consolidate NuGet packages

### PR DESCRIPTION
**Pull request by crutkas**
## PR checklist

Quick summary of changes

- Which issue does this PR relate to?
#887 
- Anything that requires particular review or attention?
nope
- Do all automated tests pass?
ones currently not broke pass.

### CODE REVIEW

**Comment by crutkas** [comment]
Check this in first, then lets reevaluate the 4.7 .NET update

**Comment by crutkas** [comment]
Reason being is we'll be playing wackamole trying to fix this with the other one

**Comment by ralarcon** [comment]
Before approve the PR, I would like to double check the Template Engine works with the  Newtonsoft.Json v10.0.0 in a vanilla machine... last time we tried didn't work.

**Comment by ralarcon** [comment]
Verified that works fine regarding the Newtonwsoft.Json v10 with this changes. By the way, I have found that changes done to allow the Big.sln work with VS2017 15.3 (issue #995 and PR #961) results in the extension not able to load in VS2017 versions previous to 15.3. I will reopen the #995.

**Comment by ralarcon** [comment]
Waiting to approve the PR until we define the strategy of TemplateEngine + Visual Studio dependencies.

**Comment by ralarcon** [comment]
Closing this pull request as it is replaced by #1011 and #1007

**Pull request closed without merging**
