### PR TITLE
Remove hidden command and WTS icon

### LINKED ISSUE #728: Right click menu not dismissing
I'm wondering if this is a repercussion of the icon addition.  In the screenshot, note the double context menu.

To repro: hover over the WTS menu item then hover over a different one.

image

i'm punting to 1.3 right now as i view this is a low priority

### PR DESCRIPTION
**Pull request by sibille**
@crutkas: This fixes #728  
Also see #620, we are the only ones with an icon on a menu as far as I can see.

### CODE REVIEW

**Comment by crutkas** [comment]
Yes, I wanted to be special for the icon, looks like it was a bad idea :)

**Comment by crutkas** [comment]
Who initially CR'ed this?  It looks ok but I didn't see how this went in the first place.

**Comment by sibille** [comment]
What do you mean by CR'ed?

**Comment by mrlacey** [comment]
I presume he meant **C**ode **R**eviewed

**Comment by sibille** [comment]
@ralarcon added the hidden command initially, so he could validate it

**Comment by sibille** [comment]
I cannot add another reviewer in. If I request a review from somebody the PR cannot proceed until he approves it?

**Comment by ralarcon** [comment]
I been side by side with Sibille regarding this, so go ahead and approve.

**Comment by crutkas** [comment]
added him

**Pull request merged**
