### PR TITLE
Migrate to Microsoft.CodeAnalysis.NetAnalyzers analyzers

### PR DESCRIPTION
**Pull request by sibille**
**Quick summary of changes**
- Migrate to Microsoft.CodeAnalysis.NetAnalyzers analyzers

**Which issue does this PR relate to?**
#3865 Migrate to NetAnalyzers analyzers

### CODE REVIEW

**Comment by mrlacey** [comment]
Is this meant to include changes for CoreTemplateSTudio too?

**Comment by sibille** [comment]
Yes, this includes updates to NetAnalyzers on CoreTemplateStudio too

**Comment by mrlacey** [comment]
> Yes, this includes updates to NetAnalyzers on CoreTemplateStudio too

Shouldn't they be made in the CoreTemplateStudio repository rather than here?

**Comment by sibille** [comment]
Thats correct. they were done on the CoreTemplateStudio in https://github.com/microsoft/CoreTemplateStudio/pull/315 and are just brought in here by the submodule update in commit https://github.com/microsoft/WindowsTemplateStudio/pull/4273/commits/c666fe259aa652e7d7846cf1722f32dd9304debe

**Review by dgomezc — APPROVED** [review]

**Pull request merged**
