### PR TITLE
Support the Image Gallery template with Caliburn.Micro

### LINKED ISSUE #1200: Port ImageGallery page to Caliburn.Micro
Now we have an image gallery page ready but it is pending to be ported to Caliburn.Micro framework.

@nigel-sampson, can you have a look on this to see if it is possible to include to the 1.4? If not we will need some time to get familiarized with the Caliburn.Micro framework.

### PR DESCRIPTION
**Pull request by nigel-sampson**
This PR adds support for Image Gallery template with the Caliburn.Micro framework.

I've been having problems with the automated tests, in particular `GenerateAllPagesAndFeaturesAndCheckWithStyleCopAsync` which fails with a json deserialization exception.

Also included is an update to one test to correctly handle the multiple dependencies of the Image Gallery templates.

Resolves #1200

### CODE REVIEW

**Comment by ralarcon** [comment]
Thanks @nigel-sampson, I had the same issue with the tests but now is going to be solved in the branch `Issue1045_uwpToolkit2.0`. I expect to have this merged today so your changes could be applied.

**Comment by nigel-sampson** [comment]
Good to know, once that's merged I'll re-merge `dev` and check the tests.

**Comment by ralarcon** [comment]
The tests now should work properly. There has been few changes which generate a conflict. We can approve the PR once the conflicts are solved.

Thanks.

**Comment by mvegaca** [comment]
Build tests fixed!

**Comment by nigel-sampson** [comment]
Thanks, having some dev machine issues last night, updated Visual Studio and the UWP tools don't want to install.

**Pull request merged**
