### PR TITLE
Issue2360 pivotpages

### PR DESCRIPTION
**Pull request by mvegaca**
Iterating between Maps / Camera #2360

### CODE REVIEW

**Comment by mvegaca** [comment]
Hi @mrlacey 
I've updated VisualBasic templates to include the Pivot Behavior.
There is a failing test on VisualBasic named **EnsureVisualBasicCodeDoesNotIncludeCommonPortingIssues** that checks Async on methods with As Task declaration. It's is failing on the IPivotPage Interface but I can't fix it because Interfaces can not declare Async Methods. Could you help me reviewing the test implementation?

**Comment by sibille** [comment]
@LeeParrishMSFT  or @milazzom, could you have a look at the prism changes?

**Comment by mrlacey** [comment]
@mvegaca I added appropriate entries for the exceptional circumstances here and tests now pass

**Comment by sibille** [comment]
thanks @mrlacey

**Pull request merged**
