### PR TITLE
Issue552 .net4.7

### PR DESCRIPTION
**Pull request by crutkas**
## PR checklist

Quick summary of changes

- Which issue does this PR relate to?
#552
- Anything that requires particular review or attention?
Nope
- Do all automated tests pass?
not due to the CI tests

### CODE REVIEW

**Comment by crutkas** [comment]
@ralarcon is this an easy item to fix or should we punt to 1.4?  I feel like just punt to 1.4 as we have a lot of additional moving parts

**Comment by ralarcon** [comment]
Adding the dependency to .NET 4.7 cause the extension not being installed in machines without this dependency.

image

Then you got the error regarding the fx missing:
image

The log states that the fx version range and ends with the error:
```
...
SupportedFrameworkVersionRange : [4.7,)
....
Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'WTS (vs2017 local)' requires a version of the .NET Framework that is not installed.
```
I notice that the machine I been working on yesterday had the .NET Fx updated automatically. Considering it is from the Creators Update, I guess there should not be too much target machines without the .NET 4.7 available. So in my opninion it is safe to include this change for this version.

I will update the PR adding the pre-requisites.

**Comment by mrlacey** [comment]
>Considering it is from the Creators Update, I guess there should not be too much target machines without the .NET 4.7 available. So in my opninion it is safe to include this change for this version.

@crutkas do you have access to any telemetry on the versions of Windows & VS people use for UWP dev? Would be good to base this on facts if we can.
We also just did a lot to maintain support for versions of VS before v15.3.  Are we now saying that wasn't as important as we now require .Net Framework 4.7 to be installed?

**Comment by crutkas** [comment]
asking

**Comment by ralarcon** [comment]
Anyway, .NET 4.7 missing can be installed by the user, the log is clear... I think it is not an stopper.

**Comment by crutkas** [comment]
yeah, i think we could just wait for 15.4 for this, no clear reason other than it would be a nice to have.

**Pull request merged**
