### PR TITLE
Update loading feedback

### PR DESCRIPTION
**Pull request by mvegaca**

### CODE REVIEW

**Comment by crutkas** [comment]
Why are you changing control types?  This feels like change just because of preference?  This goes back to #570.  There isn't a clear reason to change this.

**Comment by mvegaca** [comment]
I prefer to use Control instead of TemplatedControl because it offers more flexibility and the possibility to use TemplateBinding to access control dependency properties.

**Comment by crutkas** [comment]
@mvegaca that is developer preference and a design shift that should have been discussed.  Template binding versus just direct binding, no clear reason to adjust and break an existing pattern for a single control.

If we were going to do this, we should have had a nice quick discussion, and converted all the controls, not just one-offs.  same stuff 100% with template generated code.  we really should be living and breathing best practices.  

Right now, that isn't something that we should be doing for 1.2 release as well, we should be on stabilization and bug fixes.

**Comment by ralarcon** [comment]
Closing this PR. #618 will be fixed with the same approach using the existing control.

**Comment by ralarcon** [comment]
#570 is the issue for discussion.

**Pull request closed without merging**
