### PR TITLE
Check page/pageKey if null before navigating OnItemInvoked in ShellViewModel.cs

### PR DESCRIPTION
**Pull request by myokeeh**
# PR checklist

Quick summary of changes

- Which issue does this PR relate to? 3657
- Applies to the following platforms:
  - [X] UWP
  - [ ] WPF
- Anything that requires particular review or attention?
- Do all automated tests pass? Don't know
- Have automated tests been added for new features?
- If you've changed the UI:
  - Be sure you are including screenshots to show the changes.
  - Be sure you have reviewed the [accessibility checklist](accessibility.md).
- If you've included a new template:
  - Be sure you reviewed the [Template Verification Checklist](https://github.com/microsoft/WindowsTemplateStudio/wiki/Checklist:-Template-Verification).
  - Be sure it's included in the list on this [UWP](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/getting-started-endusers.md) or [WPF](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/WPF/getting-started-endusers.md) getting started doc.
- Have you raised issues for any needed follow-on work?
- Have docs been updated?
- If breaking changes or different ways of doing things have been introduced, have they been communicated widely?

### CODE REVIEW

**Comment by mvegaca** [comment]
Null page navigation should be handled in NavigationService Navigate method, in this way the developer only adds this validation one time instead of every time navigation calls. Working on Issue #3784 we already add a no valid navigation validation in NavigationService, please [see this pull request](https://github.com/microsoft/WindowsTemplateStudio/pull/3791) or try generating an app in Dev Nightly extension.

**Comment by myokeeh** [comment]
@mvegaca Thanks!

**Comment by myokeeh** [comment]
@mvegaca, I think I'm recalling why I did this. It was to account for cases where I didn't want navigation to occur for certain  `NavigationViewItem`s. One case is when you have nested `NavigationViewItem`s where for the top/parent, `helpers:NavHelper.NavigateTo` is NOT set because it's more of a container for children `NavigationViewItem`s

It appears even onthe latest version (wizardVersion: v3.9.20351.2, templatesVersion: v3.9.20351.2), clicking on such an `NavigationViewItem` will throw exception below.

>throw new ArgumentException(string.Format("Invalid pageKey '{0}', please provide a valid pageKey. Maybe you forgot to call NavigationService.Configure?", pageKey), nameof(pageKey));

How is WTS going to account for such a case?

**Comment by mvegaca** [comment]
Hi @myokeeh

WTS is not currently supporting non-navigation NavigationViewItems, we can study the best approach on how to implement that in future releases.

**Pull request closed without merging**
