### PR TITLE
Add multiple instances of every multiinstance template to StyleCop tests

### PR DESCRIPTION
**Pull request by sibille**
Quick summary of changes
- Add multiple instances of every multiinstance template to StyleCop G2 tests

Which issue does this PR relate to?
#3742 Add two instances of each template that is multiInstance to stylecop tests

### CODE REVIEW

**Comment by mrlacey** [comment]
In that this was prompted by an issue with the VB templates, why does this only adjust the tests of the C# code?

**Comment by sibille** [comment]
It includes VB Style tests too, anything else that should be included?

**Comment by mrlacey** [comment]
> It includes VB Style tests too, anything else that should be included?

sorry. missed that

**Comment by sibille** [comment]
No problem, I almost missed them ;)
I think it would be a good idea to include them in the BuildTemplateTests for UWP, to have them next to the stylecop tests.

**Pull request merged**
