### PR TITLE
Changed App.xaml.cs to extend Application,

### PR DESCRIPTION
**Pull request by sibille**
Added composition to CaliburnMicro to override the App.xaml.cs file,
Changed postactions on app.xaml.cs file to be added by composition templates
I also changed the path of tests to avoid errors caused by too long path.

### CODE REVIEW

**Comment by nigel-sampson** [comment]
Will merge this tonight when I have some more time and fix up the other issues on #1163

**Comment by sibille** [comment]
Added in fixes for #1082 and #1112, please check them before merging.

**Comment by nigel-sampson** [comment]
Extra commits look good, do you want to keep this PR open for any other modifications?

**Comment by sibille** [comment]
Nop, I think all review work is done.

**Comment by ralarcon** [comment]
@nigel-sampson, merging this content in order to approve #1163 and include Caliburn as part of the nightlys

**Pull request merged**
