### PR TITLE
Fix Media Player page in Caliburn Micro Framework and Pivot project.

### PR DESCRIPTION
**Pull request by dgomezc**
## PR checklist

Quick summary of changes

- Which issue does this PR relate to?
#1504

### CODE REVIEW

**Comment by ralarcon** [comment]
@mrlacey we have changed the VB implementation too. The change was simple: to use a different method from the toolkit (`FindAscendant`) to ensure we find the Pivot page where the media player page is. We requested your review just as a double check.

**Comment by ralarcon** [comment]
@mrlacey Just double checked (on both @dgomezc and me laptops) and it worked fine. 

Can you double check that the latest templates were correctly loaded to the emulator? The generated project should have the "FindAscendant / FindDescendant" method calls.

Now, to the templates being refreshed on VSEmulator or Installer (vsix running locally on the experimental instance) you would need to refresh the template engine chache (not done by default to speed up the wizard loading). You can do it by clicking "Refresh" button in the VSEmulator or, from the wizard, using a new button available in debug complilation mode which appears in the same place than the wizard / templates version numbers (clicking in the upper-left corner button).

**Comment by mrlacey** [comment]
My mistake. I was looking at the [wrong branch](https://github.com/dgomezc/WindowsTemplateStudio/tree/Issue1504-PivotAndMediaPlayerPage). 

Issue1504-PivotAndMediaPlayerPage and Issue1504-MediaPlayerPivotFix :/

**Comment by ralarcon** [comment]
No problem at all! Double checked 👍

**Pull request merged**
