### PR TITLE
Do not translate command line.

### PR DESCRIPTION
**Pull request by kxxt**
#3687

### CODE REVIEW

**Comment by sibille** [comment]
Hi @kxxt, great catch, thanks for the contribution! Not sure why the build is failing, does not seem to be related to your change!

**Comment by kxxt** [comment]
Hi @sibille. I'm also wondering why changing some resource strings would cause the build failure.

**Comment by sibille** [comment]
Must be sth else, checking the build machine...

**Comment by sibille** [comment]
Fixed! We recently updated the template engine dlls, and had to refresh the cache of the test templates

**Pull request merged**
