### PR TITLE
reference latest build of MVVM Toolkit

### LINKED ISSUE #4067: Update UWP & WPF MVVM Toolkit templates to Preview 5
Update templates to the latest preview of the MVVM Toolkit (preview 5) and retest all functioanlity.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| Yes | Yes |No |

N.B. Not including the WinUI templates in this issue as they are undergoing separate, more complicated/extensive revisions and changes.

### PR DESCRIPTION
**Pull request by mrlacey**
# PR checklist

**Quick summary of changes**

Update to preview5 of MVVM Toolkit

**Which issue does this PR relate to?**

fixes #4067

**Applies to the following platforms:**

| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
|Yes| Yes |No |

**Anything that requires particular review or attention?**

**Do all automated tests pass?**

yes

**Have automated tests been added for new features?**

n/a

**If you've changed the UI:**
  - Be sure you are including screenshots to show the changes.
  - Be sure you have reviewed the [accessibility checklist](accessibility.md).

n/a

**If you've included a new template:**
  - Be sure you reviewed the [Template Verification Checklist](https://github.com/microsoft/WindowsTemplateStudio/wiki/Checklist:-Template-Verification).
  - Be sure it's included in the list on this [UWP](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/getting-started-endusers.md) or [WPF](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/WPF/getting-started-endusers.md) getting started doc.

n/a

**Have you raised issues for any needed follow-on work?**

n/a

**Have docs been updated?**

n/a

**If breaking changes or different ways of doing things have been introduced, have they been communicated widely?**

n/a

### CODE REVIEW

**Comment by mvegaca** [comment]
Hi Matt

Working on right-click I've got some errors inferring installed packages in generated apps with MVVM Toolkit in UWP and WPF.

The package ID should be **Microsoft.Toolkit.Mvvm** instead of **Microsoft.Toolkit.MVVM**.
Can you modify this in this PR for UWP and WPF?

**Comment by mrlacey** [comment]
> Hi Matt
> 
> Working on right-click I've got some errors inferring installed packages in generated apps with MVVM Toolkit in UWP and WPF.
> 
> The package ID should be **Microsoft.Toolkit.Mvvm** instead of **Microsoft.Toolkit.MVVM**.
> Can you modify this in this PR for UWP and WPF?

What's failing?

When you say the "package ID should be **Microsoft.Toolkit.Mvvm**", why _should_ it be that? What difference does it make?

**Comment by mrlacey** [comment]
With the latest change to allow for the loading of installed apps before launching them, I can now run **_ALL_** the tests relating to MVVMTookit. - Yes, they took 28 hours to run and couldn't all be run at once because of memory consumption issues. :(

image

**Comment by mrlacey** [comment]
> > Hi Matt
> > Working on right-click I've got some errors inferring installed packages in generated apps with MVVM Toolkit in UWP and WPF.
> > The package ID should be **Microsoft.Toolkit.Mvvm** instead of **Microsoft.Toolkit.MVVM**.
> > Can you modify this in this PR for UWP and WPF?
> 
> What's failing?
> 
> When you say the "package ID should be **Microsoft.Toolkit.Mvvm**", why _should_ it be that? What difference does it make?

@mvegaca I'm reluctant to make changes to fix an issue where I can't verify that the change does fix the issue.
Additionally, if there is a standard or convention that has been broken there should be something to enforce this so this situation can be automatically detected in the future. Are you adding such enforcement? (Presumably, through the addition of appropriate tests)

**Comment by mvegaca** [comment]
I'm working on issue #4042 
I've seen that the method [ContainsSDK](https://github.com/mvegaca/WindowsTemplateStudio/blob/e105f79e953928f485a5093868fa440892fb71eb/code/src/UI/Services/ProjectConfigInfoService.cs#L480) used to infer the project metadata fails if the package id is not literally the same, in case of MVVM Toolkit, the correct way is "Microsoft.Toolkit.Mvvm", in your branch the the package id contains "MVVM" instead of "Mvvm". To fix that verification and make this code more strong I've add a lower case verification. I think that Package ID in template.json should be [Microsoft.Toolkit.Mvvm](https://www.nuget.org/packages/Microsoft.Toolkit.Mvvm/7.0.0-preview5).

Thanks ;)

**Comment by mrlacey** [comment]
> I'm working on issue #4042
> I've seen that the method [ContainsSDK](https://github.com/mvegaca/WindowsTemplateStudio/blob/e105f79e953928f485a5093868fa440892fb71eb/code/src/UI/Services/ProjectConfigInfoService.cs#L480) used to infer the project metadata fails if the package id is not literally the same, in case of MVVM Toolkit, the correct way is "Microsoft.Toolkit.Mvvm", in your branch the the package id contains "MVVM" instead of "Mvvm". To fix that verification and make this code more strong I've add a lower case verification. I think that Package ID in template.json should be [Microsoft.Toolkit.Mvvm](https://www.nuget.org/packages/Microsoft.Toolkit.Mvvm/7.0.0-preview5).
> 
> Thanks ;)

I've pushed this change but have more questions:

- In that everything else works without being case sensitive, won't the overall reliability of the system be improved if the code you've written works regardless of case too?
- If you're making changes to the WinUI files, why are you testing against the UWP & WPF templates? If there are things that could fail with those templates I'd like to add tests for them too.
- You mentioned the method `ContainsSDK` but linked to `ContainsNugetPackageCpp` which is the correct one? (I can't see anything in either that requires case sensitive checking of the PackaageID.)
- Why is that method called `ContainsNugetPackageCpp` in that it seems to have nothing to do with anything specific to C++/CPP?
- How are you planning on writing tests to verify the correct casing of referenced NuGet package names? I expect you'd need to call the NuGet API to verify the names of all the different packages. Again, it seems like it would be a lot less work (and not require extra template verification tests) if the code was not sensitive to case.

**Comment by mrlacey** [comment]
Marking as ready for review now.
If more tests are required based on the issues found by @mvegaca these can be added separately.

**Review by sibille — APPROVED** [review]

**Pull request merged**
